### ISSUE TITLE
jetson nano B01推理失败

### ISSUE THREAD

**Issue by teacher1314** [weixr18/tensorrt-alpha-ros#2]
使用的CUDA是10.2 CUDNN是8.2.1 tensorrt是8.2.1
报这个错误：
terminate called after throwing an instance of 'thrust::system::system_error'
what(): radix_sort: failed on 2nd step: cudaErrorInvalidConfiguration: invalid configuration argument
然后我定位到报错函数的函数是tensorrt-alpha-ros/src/utils/kernel_function.cu下的nmsDeviceV2函数，这个函数里面的是thrust::sort_by_key(thrust::device, p_conf, p_conf + srcHeight, p_idx, thrust::greater());这行代码问题

**Comment by teacher1314** [comment]
如果我是用nmsDeviceV1的话，可以运行，但是不知道会不会有什么影响

**Comment by weixr18** [comment]
> 使用的CUDA是10.2 CUDNN是8.2.1 tensorrt是8.2.1 报这个错误： terminate called after throwing an instance of 'thrust::system::system_error' what(): radix_sort: failed on 2nd step: cudaErrorInvalidConfiguration: invalid configuration argument 然后我定位到报错函数的函数是tensorrt-alpha-ros/src/utils/kernel_function.cu下的nmsDeviceV2函数，这个函数里面的是thrust::sort_by_key(thrust::device, p_conf, p_conf + srcHeight, p_idx, thrust::greater());这行代码问题
> 如果我是用nmsDeviceV1的话，可以运行，但是不知道会不会有什么影响

感谢反馈！看上去可能是cuda版本问题，可能10.2版本还不支持nmsDeviceV2。Jetson nano是老硬件了，最好还是搭配老一些的代码使用（
